//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar_zakaz
    {
        public int ID { get; set; }
        public int ID_zakaz { get; set; }
        public string Kod_tovar { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
